### ISSUE TITLE
X = Q @ np.diag(u) @ Q.T           ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cjh1412** [ondrolexa/polylx#1]
system： windows 10  X64
Python 2.7
using spyder 3 to calculate the length of a grain in a shp file. 
bug report: 
  File "C:\Users\pc\Anaconda2\lib\site-packages\polylx-0.4.8-py2.7.egg\polylx\core.py", line 730
    X = Q @ np.diag(u) @ Q.T
          ^
SyntaxError: invalid syntax

**Comment by cjh1412** [comment]
X = Q @ np.diag(u) @ Q.T
           ^
SyntaxError: invalid syntax

**Comment by ondrolexa** [comment]
Fixed in version 0.4.9 works in both Python 2.7 and 3.X
