### ISSUE TITLE
 Thin section photo image generating plot available ?

### ISSUE THREAD

**Issue by cycleuser** [ondrolexa/polylx#6]
This is really a masterpiece.
Thanks for the development.

Is it possible to generate grain size and shapes from rock thin section photo? And is there any related demo?

**Comment by ondrolexa** [comment]
The polylx exclusively uses the vectorized geometries of grains and the process of conversion from photo (or anything raster-based) to vector is not implemented. One reason is that there are many various strategies from fully automatic to fully manual which are appropriate for individual projects. Btw. for the digitalization of rock thin sections we mostly used manual vectorization in GIS (e.g. QGIS) to prevent undesirable artifacts and keep perfect topology.
